### ISSUE TITLE
Question for missing `train/val_vector.pth`

### ISSUE THREAD

**Issue by ranery** [i-m-vivek/EyGazing#1]
Hi, thanks for sharing such great code!

I wonder how did you generate the `train_vector.pth` and `val_vector.pth` here?
````
train_dict_vector = torch.load("train_vector.pth") 
val_dict_vector = torch.load("val_vector.pth")
````

Could you elaborate more about it, thanks!

Best,
Haoran

**Comment by ranery** [comment]
Oh, I see the pipeline! You will only run LSTM after inferencing the CNN model.

**Comment by vk-mittal14** [comment]
@ranery Yeah you are correct. I will run the CNN first and then use LSTM. Training both of them together was very slow. If you have better resources available I will suggest training them together.
